### ISSUE TITLE
tlsf_create() crashes on unaligned baseptr

### ISSUE THREAD

**Issue by ujbr** [rmind/tlsf#2]
tlsf_create() crashes if baseptr is not aligned to architecture requirements (ie ARM).  It should handle such cases by rounding up baseptr internally to nearest proper alignment (which could be #defined).

**Comment by rmind** [comment]
Yes, tlsf_create() expects `baseptr` to be aligned. The documentation should be updated. Not sure if it should perform the rounding up itself, though. I would rather check the alignment and return NULL, if it is not aligned. By the way, while `tlsf_alloc()` and `tlsf_free()` assert for the word alignment, the TLSF-EXT implementation relies only on the 2-byte alignment (but that could be eliminated too, by moving `TLSF_BLK_FREE` to the MSB, except it would reduce the space to 2GB on 32-bit architectures). At the same time, I am thinking to make `TLSF_MBS` dynamic, i.e. an argument for `tlsf_create()`.

**Comment by rmind** [comment]
I've made some improvements. Also, changed the `tlsf_create()` API. For now, MSB is still enforced to be at least 32, but I will have a look at it at some point later, once I have more free time..

Resolved. Thanks.
